#!/bin/bash
set -eo pipefail
set -x

. "$(dirname $0)/../common.sh"

set -u

threads=$1
time=$2
dst="$3"

cleanup() {
    set +e

    sudo pkill -SIGTERM iperf
}

trap cleanup EXIT

$hexec l3ep1 \
  iperf -s -p 12865 --reportstyle c \
  > "${dst}server.csv" \
  &
# $! only gives use the pid of sudo.

sleep 1

for i in $(seq 0 9)
do
  if test -e "${dst}client.csv"
  then
    # Will be 1..9
    mv -f "${dst}client.csv" "${dst}client.retry-$i.csv"
    mv -f "${dst}client.stderr" "${dst}client.retry-$i.stderr"
  fi

  # --sum-only is not supported with CSV reportstyle.
  $hexec l3h1 \
    iperf -c 20.20.20.1 -t $time -p 12865 -P $threads --reportstyle c \
    > "${dst}client.csv" \
    2> "${dst}client.stderr"

  if ! grep 'connect failed: Operation now in progress' "${dst}client.stderr"
  then
    break
  fi

  sleep 15
done

cat "${dst}client.stderr" 1>&2

sudo pkill -SIGTERM iperf
wait

if grep 'connect failed' "${dst}client.stderr"
then
  exit 1
fi
