#!/bin/bash
set -eo pipefail
set -x

. "$(dirname $0)/../common.sh"

set -u

threads=$1
time=$2
dst="$3"

cleanup() {
    set +e

    sudo pkill -SIGTERM iperf3
}

trap cleanup EXIT

echo '{"error": "not tried yet"}' > "${dst}client.json"
i=4
while grep '"error":' "${dst}client.json"
do
    if [ $i -ge 32 ]
    then
        exit 1
    fi

    sleep $i

    $hexec l3ep1 \
        taskset --cpu-list $threads-$(expr $threads + $threads - 1) \
        iperf3 --server -p 12865 --json \
        | tee "${dst}server.json" &
    # $! only gives use the pid of sudo.

    sleep $i

    $hexec l3h1 \
        taskset --cpu-list 0-$(expr $threads - 1) \
        iperf3 -c 20.20.20.1 -t $time -p 12865 -P $threads --json \
        --connect-timeout $((i*1000)) --snd-timeout $((i*1000)) \
        | tee "${dst}client.json"

    sudo pkill -SIGTERM iperf3
    wait

    i=$((i*2))
done
